# ===============================
# common
# ===============================

spring:
  security:

    # OAuth2 Social Login
    oauth2:
      client:
        registration:

          # Google
          google:
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID}         # Oauth2 google client id
            client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET} # Oauth2 google client secret
            scope:
              - profile
              - email

          # Naver
          naver:
            client-id: ${OAUTH2_NAVER_CLIENT_ID}          # Oauth2 naver client id
            client-secret: ${OAUTH2_NAVER_CLIENT_SECRET}  # Oauth2 naver client secret
            redirect-uri: ${OAUTH2_NAVER_REDIRECT_URL}
            client-name: Naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email

        # naver, kakao 같은 경우는 oauth2-client 라이브러리에 정보가 없음
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # JSON key value : response



# ===============================
# profile - local
# ===============================
---
spring:
  config:
    activate:
      on-profile: local

logging:
  level:
    org.springframework.security: INFO #DEBUG
    org.springframework.web.servlet.resource: INFO #TRACE


# ===============================
# profile - prod
# ===============================
---
spring:
  config:
    activate:
      on-profile: prod

