name: Test SSH Connection

on:
  workflow_dispatch:  # 수동 실행

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Show Secrets (masked)
        run: |
          echo "EC2_HOST length: ${#EC2_HOST}"
          echo "EC2_USERNAME length: ${#EC2_USERNAME}"
          echo "EC2_SSH_KEY length: ${#EC2_SSH_KEY}"
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

      - name: Test SSH with verbose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          timeout: 30s
          command_timeout: 1m
          debug: true
          script: |
            echo "=== SSH Connection Successful ==="
            whoami
            hostname
            pwd
            date